# Generated by Django 3.1.4 on 2021-01-04 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiBilal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
