# Generated by Django 3.1.4 on 2021-01-04 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apiBilal', '0002_auto_20210104_1927'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libro',
            name='id',
        ),
        migrations.RemoveField(
            model_name='prestamo',
            name='id',
        ),
        migrations.AlterField(
            model_name='libro',
            name='titulo',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='libro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='apiBilal.libro'),
        ),
    ]
